Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -116,15 +116,15 @@ jobs:
             heroku plugins:install heroku-cli-deploy
             heroku plugins:install heroku-cli-deploy  # when debugging on circle image, first run succeeded, but did not make plugin available
             heroku deploy:jar standalone-app.jar --app spring-api-pet
-      - run:
-          name: Smoke Test
-          command: |
-            # Heroku deploy command will pass even if application crashes. Simple smoke test to make sure app is up.
-            HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://spring-api-pet.herokuapp.com`
-            if [ "$HTTPCODE" -ne 200 ];then
-              echo "heroku app not responding, failing deploy"
-              exit 1
-            fi
+#       - run:
+#           name: Smoke Test
+#           command: |
+#             # Heroku deploy command will pass even if application crashes. Simple smoke test to make sure app is up.
+#             HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://spring-api-pet.herokuapp.com`
+#             if [ "$HTTPCODE" -ne 200 ];then
+#               echo "heroku app not responding, failing deploy"
+#               exit 1
+#             fi
 #   deploy-cf:
 #     docker:
 #       - image: eddiewebb/queue-circleci-openjdk:8-jdk-browsers
